import Head from "next/head";
import fetch from 'isomorphic-unfetch' ; 


export default function Home({questions}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {questions[0].question} ouael
    </div>
  );
}

Home.getInitialProps = async (ctx) =>{
  const res = await fetch('http://localhost:3000/api/questions'); 
  const data = await res.json() ; 
  return {questions : data }
}
